const avatarDir = 'lib/images/licensed/avatars';

const avatarOptions = [
  // ── Music ──
  ('music-note.svg', 'Music Note'),
  ('guitar.svg', 'Guitar'),
  ('piano.svg', 'Piano'),
  ('violin.svg', 'Violin'),
  ('drums.svg', 'Drums'),
  ('microphone.svg', 'Microphone'),
  ('music-player.svg', 'Music Player'),
  ('vinyl.svg', 'Vinyl'),
  // ── Animals ──
  ('bee.svg', 'Bee'),
  ('bulldog.svg', 'Bulldog'),
  ('cat.svg', 'Cat'),
  ('chicken.svg', 'Chicken'),
  ('cow.svg', 'Cow'),
  ('duck.svg', 'Duck'),
  ('elephant.svg', 'Elephant'),
  ('fox.svg', 'Fox'),
  ('frog.svg', 'Frog'),
  ('giraffe.svg', 'Giraffe'),
  ('kangaroo.svg', 'Kangaroo'),
  ('lion.svg', 'Lion'),
  ('monkey.svg', 'Monkey'),
  ('mouse.svg', 'Mouse'),
  ('octopus.svg', 'Octopus'),
  ('owl.svg', 'Owl'),
  ('panda.svg', 'Panda'),
  ('penguin.svg', 'Penguin'),
  ('rabbit.svg', 'Rabbit'),
  ('shark.svg', 'Shark'),
  ('siberian-husky.svg', 'Husky'),
  ('sloth.svg', 'Sloth'),
  ('tiger.svg', 'Tiger'),
  ('turtle.svg', 'Turtle'),
  ('whale.svg', 'Whale'),
];
